/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SpeedRead {
        "pause": () => Promise<void>;
        "start": () => Promise<void>;
        "stop": () => Promise<void>;
        "text": string;
        "wpm": number;
    }
}
declare global {
    interface HTMLSpeedReadElement extends Components.SpeedRead, HTMLStencilElement {
    }
    var HTMLSpeedReadElement: {
        prototype: HTMLSpeedReadElement;
        new (): HTMLSpeedReadElement;
    };
    interface HTMLElementTagNameMap {
        "speed-read": HTMLSpeedReadElement;
    }
}
declare namespace LocalJSX {
    interface SpeedRead {
        "text"?: string;
        "wpm"?: number;
    }
    interface IntrinsicElements {
        "speed-read": SpeedRead;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "speed-read": LocalJSX.SpeedRead & JSXBase.HTMLAttributes<HTMLSpeedReadElement>;
        }
    }
}
